; This program will throw a custom runtime exception
; I was being lazy with this program(did not put inside function)

throw 15 27 "CustomException" "This is a custom exception."

halt      ; this will not be reached
